{
 "title": "HP iLO (hpilo-exporter, dashboard 13709)",
 "description": "HP iLO Metrics Exporter\n\n\nThe information displayed in this dashboard\n\n‍‍‍‍\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hpilo_firmware_version", "legendFormat": "{{ilo_host}}" }
   ]
  },
  {
   "title": "Hardware error in Tabriz",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hpilo_storage ) and (hpilo_fans) and (hpilo_memory) and (hpilo_power_supplies) and (hpilo_processor) and (hpilo_temperature)",
     "legendFormat": "{{ilo_host}} "
    }
   ]
  },
  {
   "title": "hpilo fans",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hpilo_fans", "legendFormat": "{{ilo_host}} " }
   ]
  },
  {
   "title": "hpilo_bios_hardware",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hpilo_bios_hardware", "legendFormat": "{{ilo_host}} " }
   ]
  },
  {
   "title": "hpilo processor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hpilo_processor", "legendFormat": "{{ilo_host}} " }
   ]
  },
  {
   "title": "hpilo_power_supplies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hpilo_power_supplies", "legendFormat": "{{ilo_host}} " }
   ]
  },
  {
   "title": "hpilo_storage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hpilo_storage", "legendFormat": "{{ilo_host}}" }
   ]
  },
  {
   "title": "hpilo_memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hpilo_memory", "legendFormat": "{{ilo_host}} " }
   ]
  }
 ]
}